batchSize: 10
rateLimit: 200
sendWebhook: true
Log0Wallets: false
ETHChain: true
BSCChain: true
EthRpcList:
  - https://ethereum-rpc.publicnode.com
  - https://eth.drpc.org
  - https://eth.llamarpc.com
BscRpcList:
  - https://bsc-dataseed1.binance.org
  - https://bsc-dataseed2.binance.org
  - https://bsc-dataseed3.binance.org

#Use infura,ankr,... rpc
